export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const VALIDAR_FORMULARIO_EXITO = 'VALIDAR_FORMULARIO_EXITO';
export const VALIDAR_FORMULARIO_ERROR = 'VALIDAR_FORMULARIO_ERROR';

export const AGREGAR_PUBLICACION = 'AGREGAR_PUBLICACION';
export const AGREGAR_PUBLICACION_EXITO = 'AGREGAR_PUBLICACION_EXITO';
export const AGREGAR_PUBLICACION_ERROR = 'AGREGAR_PUBLICACION_ERROR';

export const COMENZAR_DESCARGA_PUBLICACIONES = 'COMENZAR_DESCARGA_PUBLICACIONES';
export const DESCARGA_PUBLICACIONES_EXITOSA = 'DESCARGA_PUBLICACIONES_EXITOSA';
export const DESCARGA_PUBLICACIONES_ERROR = 'DESCARGA_PUBLICACIONES_ERROR';

export const OBTENER_PUBLICACION_ELIMINAR = 'OBTENER_PUBLICACION_ELIMINAR';
export const PUBLICACION_ELIMINADO_EXITO = 'PUBLICACION_ELIMINADO_EXITO';
export const PUBLICACION_ELIMINADO_ERROR = 'PUBLICACION_ELIMINADO_ERROR';

export const OBTENER_PUBLICACION_EDITAR = 'OBTENER_PUBLICACION_EDITAR';
export const PUBLICACION_EDITAR_EXITO = 'PUBLICACION_EDITAR_EXITO';
export const PUBLICACION_EDITAR_ERROR = 'PUBLICACION_EDITAR_ERROR'

export const COMENZAR_EDICION_PUBLICACION = 'COMENZAR_EDICION_PUBLICACION';
export const PUBLICACION_EDITADO_EXITO = 'PUBLICACION_EDITADO_EXITO';
export const PUBLICACION_EDITADO_ERROR = 'PUBLICACION_EDITADO_ERROR';